name: deploy-to-ipfs

on:
    push:
        paths:
            - '**.elm'
            - 'static/**'

jobs:
    elm-build:
        name: Build website using Elm
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - uses: jorelali/setup-elm@v2
            with:
                elm-version: 0.19.1
          - name: Build website with Elm
            run: |
                mkdir pub
                cp -r static/* pub
                elm make src/Main.elm --optimize --output pub/elm.js
          - name: Upload artifact
            uses: actions/upload-artifact@v2
            with:
                name: built-website
                path: pub

    ipfs-deploy:
        name: Load dat cat on a rocket to OUTER SPACE >:3
        needs: elm-build
        runs-on: ubuntu-latest
        environment: IPFS
        steps:
          - name: Retrieve built website
            uses: actions/download-artifact@v2
            with:
                name: built-website
                path: pub
          - name: Add to Pinata
            id: pin
            uses: aquiladev/ipfs-action@v0.1.5
            with:
                path: pub
                service: pinata
                pinataKey: ${{ secrets.PINATA_KEY }}
                pinataSecret: ${{ secrets.PINATA_SECRET }}
                pinataPinName: 'arrete.chat'
          - name: Update DNSLink
            uses: textileio/cloudflare-update-dnslink@v2
            with:
                cid: ${{ steps.pin.outputs.hash }}
            env:
                RECORD_NAME: '_dnslink'
                RECORD_DOMAIN: 'arrete.chat'
                CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
                CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONEID }}
