name: deploy-to-ipfs

on:
    push:
        paths:
            - '**.elm'
            - 'pub/**'

jobs:
    elm-build:
        name: Build website using Elm
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - uses: jorelali/setup-elm@v2
            with:
                elm-version: 0.19.1
          - name: Build website with Elm
            run: |
                mkdir pub
                cp -r static/* pub
                elm make src/Main.elm --optimize --output pub/elm.js
          - name: Upload artifact
            uses: actions/upload-artifact@v2
            with:
                name: built-website
                path: pub

    ipfs-deploy:
        name: Load dat cat on a rocket to OUTER SPACE >:3
        needs: elm-build
        runs-on: ubuntu-latest
        environment: IPFS
        steps:
          - name: Retrieve built website
            uses: actions/download-artifact@v2
            with:
                name: built-website
                path: pub
          - name: Add to IPFS
            uses: quorumcontrol/ipfs-deploy-github-action@v1.1
            with:
                deploy-dir: pub
                pinata-api-key: ${{ secrets.PINATA_KEY }}
                pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
                cloudflare-api-token: ${{ secrets.CLOUDFLARE_TOKEN }}
                cloudflare-zone: arrete.chat
                cloudflare-record: _dnslink.arrete.chat


